# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](green bold)' 
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bold white"
truncation_length = 30

[git_status]
conflicted = "⚔️ "

[directory]
style = "blue"

[[battery.display]]
threshold = 30
style = "bold red"

[rust]
style = "bold white"

