require("irina.plugins-setup")
require("irina.core.keymaps")
require("irina.core.options")
require("irina.core.colorscheme")
require("irina.plugins.comment")
require("irina.plugins.nvim-tree")
require("irina.plugins.lualine")
require("irina.plugins.telescope")
require("irina.plugins.nvim-cmp")
require("irina.plugins.lsp.mason")
require("irina.plugins.lsp.lspsaga")
require("irina.plugins.lsp.lspconfig")
require("irina.plugins.lsp.null-ls")
require("irina.plugins.autopairs")
require("irina.plugins.treesitter")
require("irina.plugins.gitsigns")

