# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml

# A minimal left prompt
#format = """$character"""

# move the rest of the prompt to the right
#right_format = """$all"""

# Inserts a blank line between shell prompts
#add_newline = true 

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](green bold)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bold white"
truncation_length = 30

[git_status]
conflicted = "⚔️ "

[directory]
style = "bold yellow"

[[battery.display]]
threshold = 30
style = "bold red"

[rust]
style = "bold white"

